debug: false

server:
  host: 0.0.0.0
  port: 7080

logging:
  path: ./var/log
  filename:
    template: flow-{id}.log

  formatters:
    prefect:
      class: prefect.logging.formatters.PrefectFormatter
      format: "%(asctime)s.%(msecs)03d | %(levelname)-7s | %(name)s - %(message)s"
      flow_run_fmt: "%(asctime)s.%(msecs)03d | %(levelname)-7s | Flow run %(flow_run_name)r - %(message)s"
      task_run_fmt: "%(asctime)s.%(msecs)03d | %(levelname)-7s | Task run %(task_run_name)r - %(message)s"
      datefmt: "%H:%M:%S"

spack:
  manifest:
    name: spack.yaml
    config:
      view: false
      concretizer:
        unify: when_possible
      container:
        images:
          os: ubuntu:20.04
          spack: v0.19.2
        format: singularity
        template: container/singularity_base.def
        strip: true
        os_packages:
          build:
            - libclang-dev
            - libfribidi-dev
            - libharfbuzz-dev
            - libhdf5-dev
            - libpq5
            - libxt-dev
            - lsb-release
            - psmisc
            - sudo
          final:
            - libgfortran5
            - libgomp1
            - libpq5
            - sqlite3

singularity:
  command: singularity
  spec: singularity.def
  image: singularity.sif

artifacts:
  repo:
    uri: https://github.com/user/project
    token:

  oras:
    - username:
      token:
