debug: false

server:
  host: 0.0.0.0
  port: 7080

spack:
  command: spack
  manifest:
    name: spack.yaml
    config:
      view: false
      concretizer:
        unify: when_possible
      container:
        images:
          os: ubuntu:20.04
          spack: v0.19.1
        format: singularity
        strip: true
        os_packages:
          final:
            - libgomp1
            - libgfortran5

singularity:
  command: singularity
  spec: singularity.def
  image: singularity.sif

artifacts:
  repo:
    uri: https://github.com/user/project
    token:

  oras:
    - username:
      token:
