# This is a basic workflow to help you get started with Actions

name: tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: ["3.11"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry tox tox-gh-actions

      - name: Install Spack
        uses: actions/checkout@v3
        with:
          repository: spack/spack
          ref: v0.19.1
          path: spack

      - name: Create config file
        env:
          CONFIG_PATH: ~/.softpack/builder
          CONFIG_FILE: config.yml
          SPACK_COMMAND: $GITHUB_WORKSPACE/spack/bin/spack
        run: |
          mkdir -p $CONFIG_PATH
          cat <<EOF > $CONFIG_PATH/$CONFIG_FILE
          spack:
            command: $SPACK_COMMAND
          EOF
          pwd
          ls -al .
          cat $CONFIG_PATH/$CONFIG_FILE

      - name: test with tox
        run:
          tox

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
          files: coverage.xml
